### ISSUE TITLE
Implement main page

### ISSUE THREAD

**Issue by ananafrida** [ananafrida/comp-333-4-frontend#12]

**Comment by n-aggarwal** [comment]
Deadline: November  11, 11:59pm

**Comment by n-aggarwal** [comment]
When you implement the main page, please make it so that each component has an "update" button, "read" and a "delete" button. Also, when the button is pressed the user is navigated to a "update" page, "read" page and a "delete" page. Also please pass the params: <br />

Delete: id 
Update: song, artist, username, rating, and id. 
read: song, artist, username, rating, and id. 

I have passed params from register and login to main. You can take a look at those to see as to how to pass params in stack navigation, if needed.

**Comment by ananafrida** [comment]
I will take care of the delete and update params under my update and delete tickets. For your read song, please feel free to edit the main.js for the purposes of read params as needed.
